import { CHARACTER_IDS } from '../config.js';

export const cr7 = {
  id: CHARACTER_IDS.cr7,
  name: 'CR7',
  maxHealth: 1050,
  speed: 190,
  radius: 30,
  normalAttack: 'Football Kick',
  normalDamage: 50,
  attackCooldown: 500,
  normalRange: 720,
  specialSkill: 'Siu',
  specialDamage: 220,
  description: 'Long-range striker who fires footballs like bullets and celebrates Siu for a guaranteed hit.',
  color: '#d90429',
  accentColor: '#f8f9fa',
  image: 'assets/characters/cr7.png',
  normalProjectile: {
    type: 'football',
    label: 'Football Kick',
    speed: 760,
    radius: 12,
    color: '#f8f9fa',
    knockback: 60,
    shape: 'circle',
    image: 'assets/effects/football.svg',
  },
  special: {
    type: 'siu',
    label: 'Siu',
    speed: 0,
    radius: 34,
    color: '#f72585',
    knockback: 180,
    shape: 'circle',
    flash: 'siu',
    sound: 'assets/sounds/siu.mp3',
    guaranteedHit: true,
    avatarImage: 'assets/effects/siu.png',
    avatarDuration: 900,
  },
};
